// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package server

import (
	"context"

	"tiny-tiktok/service/relation/internal/logic"
	"tiny-tiktok/service/relation/internal/svc"
	"tiny-tiktok/service/relation/relation"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ServiceServer) Action(ctx context.Context, in *relation.ActionRequest) (*relation.ActionResponse, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *ServiceServer) FollowList(ctx context.Context, in *relation.FollowListRequest) (*relation.FollowListResponse, error) {
	l := logic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

func (s *ServiceServer) FollowerList(ctx context.Context, in *relation.FollowerListRequest) (*relation.FollowerListResponse, error) {
	l := logic.NewFollowerListLogic(ctx, s.svcCtx)
	return l.FollowerList(in)
}

func (s *ServiceServer) FriendList(ctx context.Context, in *relation.FriendListRequest) (*relation.FriendUserResponse, error) {
	l := logic.NewFriendListLogic(ctx, s.svcCtx)
	return l.FriendList(in)
}
