// Code generated by hertz generator.

package main

import (
	"os"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/justGoRun/tinyTiktok/biz/repository"
)

func main() {
	if err := Init(); err != nil {
		os.Exit(-1)
	}

	h := server.Default()

	register(h)
	h.Spin()
}

func Init() error {
	if err := repository.Init(); err != nil {
		return err
	}

	return nil
}
