// Code generated by hertz generator.

package douyin_core

import (
	"context"

	"github.com/justGoRun/tinyTiktok/biz/model/douyin_core"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Feed .
// @router /douyin/feed/ [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req douyin_core.DouyinFeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	msg := "feed"
	resp := douyin_core.DouyinFeedResponse{
		StatusCode: nil,
		StatusMsg:  &msg,
		VideoList:  nil,
		NextTime:   nil,
	}

	c.JSON(consts.StatusOK, resp)
}
