// Code generated by hertz generator.

package douyin_core

import (
	"context"

	"github.com/justGoRun/tinyTiktok/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
)

// Login .
// @router /douyin/user/login/ [POST]
func Login_mw(ctx context.Context, c *app.RequestContext) {
	username := c.Query("username")
	password := c.Query("password")

	user_id, err := service.Login(username, password)
	if err != nil {
		// c.JSON(http.StatusOK, UserLoginResponse{
		// 	UserId: -1,
		// })
		c.Set("status_msg", err.Error())
	} else {
		// c.JSON(http.StatusOK, UserLoginResponse{
		// 	UserId: user_id,
		// })
		// return user_id, ni
		c.Set("user_id", user_id)
	}
}

func Login(ctx context.Context, c *app.RequestContext) {
}
