// Code generated by hertz generator.

package douyin_core

import (
	"context"

	"github.com/justGoRun/tinyTiktok/biz/model/douyin_core"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// List .
// @router /douyin/publish/list/ [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req douyin_core.DouyinPublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	msg := "list"
	resp := douyin_core.DouyinPublishListResponse{
		StatusCode: nil,
		StatusMsg:  &msg,
		VideoList:  nil,
	}

	c.JSON(consts.StatusOK, resp)
}
