// Code generated by hertz generator.

package douyin_core

import (
	"context"

	"github.com/justGoRun/tinyTiktok/biz/model/douyin_core"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Action .
// @router /douyin/publish/action/ [POST]
func Action(ctx context.Context, c *app.RequestContext) {
	var err error
	var req douyin_core.DouyinPublishActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	msg := "action"
	resp := douyin_core.DouyinPublishActionResponse{
		StatusCode: nil,
		StatusMsg:  &msg,
	}

	c.JSON(consts.StatusOK, resp)
}
