// Code generated by hertz generator.

package douyin_core

import (
	"context"

	"github.com/justGoRun/tinyTiktok/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
)

// Register .
// @router /douyin/user/register/ [POST]
func Register_mw(ctx context.Context, c *app.RequestContext) {
	username := c.Query("username")
	password := c.Query("password")

	user_id, err := service.Register(username, password)

	if err != nil {
		// c.JSON(http.StatusOK, UserLoginResponse{
		// 	Response: Response{
		// 		StatusCode: 1,
		// 		StatusMsg:  err.Error()},
		// })
		c.Set("status_msg", err.Error())
	} else {
		// c.JSON(http.StatusOK, UserLoginResponse{
		// 	Response: Response{
		// 		StatusCode: 0,
		// 		StatusMsg:  "Register success"},
		// 	UserId: user_id,
		// })
		c.Set("user_id", user_id)
	}
}

func Register(ctx context.Context, c *app.RequestContext) {

}
