// Code generated by hertz generator.

package douyin_core

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/justGoRun/tinyTiktok/biz/model/douyin_core"
)

// User .
// @router /douyin/user/ [GET]
func User(ctx context.Context, c *app.RequestContext) {
	var err error
	var req douyin_core.DouyinUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	msg := "user"
	resp := douyin_core.DouyinUserResponse{
		StatusCode: nil,
		StatusMsg:  &msg,
		User:       nil,
	}

	c.JSON(consts.StatusOK, resp)
}
