// Code generated by goctl. DO NOT EDIT.
// Source: feed.proto

package server

import (
	"context"

	"tiny-tiktok/service/feed/internal/logic"
	"tiny-tiktok/service/feed/internal/svc"
	"tiny-tiktok/service/feed/pb/feed"
)

type FeedServiceServer struct {
	svcCtx *svc.ServiceContext
	feed.UnimplementedFeedServiceServer
}

func NewFeedServiceServer(svcCtx *svc.ServiceContext) *FeedServiceServer {
	return &FeedServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FeedServiceServer) Feed(ctx context.Context, in *feed.FeedRequest) (*feed.FeedResponse, error) {
	l := logic.NewFeedLogic(ctx, s.svcCtx)
	return l.Feed(in)
}
