// Code generated by goctl. DO NOT EDIT.
// Source: publish.proto

package server

import (
	"context"

	"tiny-tiktok/service/publish/internal/logic"
	"tiny-tiktok/service/publish/internal/svc"
	"tiny-tiktok/service/publish/pb/publish"
)

type PublishServiceServer struct {
	svcCtx *svc.ServiceContext
	publish.UnimplementedPublishServiceServer
}

func NewPublishServiceServer(svcCtx *svc.ServiceContext) *PublishServiceServer {
	return &PublishServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PublishServiceServer) PublishAction(ctx context.Context, in *publish.PublishActionReq) (*publish.PublishActionResp, error) {
	l := logic.NewPublishActionLogic(ctx, s.svcCtx)
	return l.PublishAction(in)
}

func (s *PublishServiceServer) PublishList(ctx context.Context, in *publish.PublishListReq) (*publish.PublishListResp, error) {
	l := logic.NewPublishListLogic(ctx, s.svcCtx)
	return l.PublishList(in)
}
