// Code generated by goctl. DO NOT EDIT.
// Source: feed.proto

package feedservice

import (
	"context"

	"tiny-tiktok/service/feed/pb/feed"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FeedRequest  = feed.FeedRequest
	FeedResponse = feed.FeedResponse
	User         = feed.User
	Video        = feed.Video

	FeedService interface {
		Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error)
	}

	defaultFeedService struct {
		cli zrpc.Client
	}
)

func NewFeedService(cli zrpc.Client) FeedService {
	return &defaultFeedService{
		cli: cli,
	}
}

func (m *defaultFeedService) Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	client := feed.NewFeedServiceClient(m.cli.Conn())
	return client.Feed(ctx, in, opts...)
}
