// Code generated by hertz generator.

package douyin_core

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/justGoRun/tinyTiktok/biz/handler/douyin_core"
)

var authMidware = authMidwareInit()

func rootMw() []app.HandlerFunc {
	// your code..
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feed0Mw() []app.HandlerFunc {
	// your code...
	_feed0Mw := []app.HandlerFunc{authMidware.MiddlewareFunc()}
	return _feed0Mw
}

func _publishMw() []app.HandlerFunc {
	// your code...
	_publishMw := []app.HandlerFunc{authMidware.MiddlewareFunc()}
	return _publishMw
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _action0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	_user0Mw := []app.HandlerFunc{authMidware.LoginHandler}
	return _user0Mw
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _login0Mw() []app.HandlerFunc {
	// your code...
	_login0Mw := []app.HandlerFunc{authMidware.LoginHandler}
	return _login0Mw
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _register0Mw() []app.HandlerFunc {
	// your code...

	_register0Mw := []app.HandlerFunc{
		func(ctx context.Context, c *app.RequestContext) {
			douyin_core.Register_mw(ctx, c)
			c.Set("type", "register")
			authMidware.LoginHandler(ctx, c)
		}}
	return _register0Mw
}
