// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package server

import (
	"context"

	"tiny-tiktok/service/favorite/internal/logic"
	"tiny-tiktok/service/favorite/internal/svc"
	"tiny-tiktok/service/favorite/pb/favorite"
)

type FavoriteServiceServer struct {
	svcCtx *svc.ServiceContext
	favorite.UnimplementedFavoriteServiceServer
}

func NewFavoriteServiceServer(svcCtx *svc.ServiceContext) *FavoriteServiceServer {
	return &FavoriteServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteServiceServer) FavoriteAction(ctx context.Context, in *favorite.FavoriteActionReq) (*favorite.FavoriteActionResp, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}

func (s *FavoriteServiceServer) FavoriteList(ctx context.Context, in *favorite.FavoriteListReq) (*favorite.FavoriteListResp, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}
