// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package server

import (
	"context"

	"tiny-tiktok/service/favorite/internal/logic"
	"tiny-tiktok/service/favorite/internal/svc"
	"tiny-tiktok/service/favorite/pb/favorite"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	favorite.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) FavoriteAction(ctx context.Context, in *favorite.FavoriteActionReq) (*favorite.FavoriteActionResp, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}

func (s *UserServiceServer) FavoriteList(ctx context.Context, in *favorite.FavoriteListReq) (*favorite.FavoriteListResp, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}
