// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"tiny-tiktok/service/message/internal/logic"
	"tiny-tiktok/service/message/internal/svc"
	"tiny-tiktok/service/message/pb/message"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServiceServer) Chat(ctx context.Context, in *message.DouyinMessageChatRequest) (*message.DouyinMessageChatResponse, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}

func (s *MessageServiceServer) Action(ctx context.Context, in *message.DouyinRelationActionRequest) (*message.DouyinRelationActionResponse, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}
