// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/justGoRun/tinyTiktok/biz/router/douyin_core"
	"github.com/cloudwego/hertz/pkg/app/server"

)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	douyin_core.Register(r)
}
