// Code generated by goctl. DO NOT EDIT.
package types

type FeedReq struct {
	LatestTime string `form:"latest_time,optional"` // 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
	Token      string `form:"token,optional"`       // 用户登录状态下设置
}

type FeedResp struct {
	NextTime   int64   `json:"next_time"`            // 本次返回的视频中，发布最早的时间，作为下次请求时的latest_time
	StatusCode int32   `json:"status_code,optional"` // 状态码，0-成功，其他值-失败
	StatusMsg  string  `json:"status_msg"`           // 返回状态描述
	VideoList  []Video `json:"video_list,optional"`  // 视频列表
}

type Video struct {
	Author        User   `json:"author"`         // 视频作者信息
	CommentCount  int64  `json:"comment_count"`  // 视频的评论总数
	CoverURL      string `json:"cover_url"`      // 视频封面地址
	FavoriteCount int64  `json:"favorite_count"` // 视频的点赞总数
	ID            int64  `json:"id"`             // 视频唯一标识
	IsFavorite    bool   `json:"is_favorite"`    // true-已点赞，false-未点赞
	PlayURL       string `json:"play_url"`       // 视频播放地址
	Title         string `json:"title"`          // 视频标题
}

type User struct {
	Avatar          string `json:"avatar,optional"`          // 用户头像
	BackgroundImage string `json:"background_image"`         // 用户个人页顶部大图
	FavoriteCount   int64  `json:"favorite_count,optional"`  // 喜欢数
	FollowCount     int64  `json:"follow_count,optional"`    // 关注总数
	FollowerCount   int64  `json:"follower_count,optional"`  // 粉丝总数
	ID              int64  `json:"id"`                       // 用户id
	IsFollow        bool   `json:"is_follow"`                // true-已关注，false-未关注
	Name            string `json:"name"`                     // 用户名称
	Signature       string `json:"signature,optional"`       // 个人简介
	TotalFavorited  int64 `json:"total_favorited,optional"` // 获赞数量
	WorkCount       int64  `json:"work_count,optional"`      // 作品数
}

type LoginReq struct {
	Username string `form:"username"` // 注册用户名，最长32个字符
	Password string `form:"password"` // 密码，最长32个字符
}

type LoginResp struct {
	StatusCode int64  `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg,optional"` // 返回状态描述
	Token      string `json:"token"`               // 用户鉴权token
	UserID     int64  `json:"user_id"`             // 用户id
}

type RegisterReq struct {
	Password string `form:"password"` // 密码，最长32个字符
	Username string `form:"username"` // 注册用户名，最长32个字符
}

type RegisterResp struct {
	StatusCode int64  `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg,optional"` // 返回状态描述
	Token      string `json:"token"`               // 用户鉴权token
	UserID     int64  `json:"user_id"`             // 用户id
}

type UserInfoReq struct {
	Token  string `form:"token"`   // 用户鉴权token
	UserID string `form:"user_id"` // 用户id
}

type UserInfoResp struct {
	StatusCode int64  `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg,optional"` // 返回状态描述
	User       User   `json:"user"`                // 用户信息
}

type PublishActionReq struct {
	Token string `form:"token,omitempty"` // 用户登录状态下设置
	Data  []byte `form:"data"`
	Title string `form:"title"`
}

type PublishActionResp struct {
	StatusCode int64  `json:"status_code"`
	StatusMsg  string `json:"status_msg,optional"`
}

type PublishListReq struct {
	Token  string `form:"token"`   // 用户鉴权token
	UserID string `form:"user_id"` // 用户id
}

type PublishListResp struct {
	StatusCode int64   `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string  `json:"status_msg,optional"` // 返回状态描述
	VideoList  []Video `json:"video_list"`          // 用户发布的视频列表
}

type FavoriteActionReq struct {
	ActionType string `form:"action_type"` // 1-点赞，2-取消点赞
	Token      string `form:"token"`       // 用户鉴权token
	VideoID    string `form:"video_id"`    // 视频id
}

type FavoriteActionResp struct {
	StatusCode int64  `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg,optional"` // 返回状态描述
}

type FavoriteListReq struct {
	Token  string `form:"token"`   // 用户鉴权token
	UserID string `form:"user_id"` // 用户id
}

type FavoriteListResp struct {
	StatusCode string  `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string  `json:"status_msg,optional"` // 返回状态描述
	VideoList  []Video `json:"video_list"`          // 用户点赞视频列表
}

type CommentActionReq struct {
	ActionType  string `form:"action_type"`           // 1-发布评论，2-删除评论
	CommentID   string `form:"comment_id,optional"`   // 要删除的评论id，在action_type=2的时候使用
	CommentText string `form:"comment_text,optional"` // 用户填写的评论内容，在action_type=1的时候使用
	Token       string `form:"token"`                 // 用户鉴权token
	VideoID     string `form:"video_id"`              // 视频id
}

type CommentActionResp struct {
	Comment    Comment `json:"comment"`              // 评论成功返回评论内容，不需要重新拉取整个列表
	StatusCode int64   `json:"status_code,optional"` // 状态码，0-成功，其他值-失败
	StatusMsg  string  `json:"status_msg"`           // 返回状态描述
}

type Comment struct {
	Content    string `form:"content"`     // 评论内容
	CreateDate string `form:"create_date"` // 评论发布日期，格式 mm-dd
	ID         int64  `form:"id"`          // 评论id
	User       User   `form:"user"`        // 评论用户信息
}

type CommentListReq struct {
	Token   string `form:"token,optional"` // 用户鉴权token
	VideoID string `form:"video_id"`       // 视频id
}

type CommentListResp struct {
	CommentList []Comment `json:"comment_list"`         // 评论列表
	StatusCode  int64     `json:"status_code,optional"` // 状态码，0-成功，其他值-失败
	StatusMsg   string    `json:"status_msg"`           // 返回状态描述
}

type RelationActionReq struct {
	ActionType string `form:"action_type"` // 1-关注，2-取消关注
	ToUserID   string `form:"to_user_id"`  // 对方用户id
	Token      string `form:"token"`       // 用户鉴权token
}

type RelationActionResp struct {
	StatusCode int64  `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg,optional"` // 返回状态描述
}

type FriendUser struct {
	User    User   `json:"user"`
	Message string `json:"message,optional"`
	MsgTyep int    `json:"msg_type"`
}

type RelationFollowListReq struct {
	Token  string `form:"token"`   // 用户鉴权token
	UserID string `form:"user_id"` // 用户id
}

type RelationFollowListResp struct {
	StatusCode string       `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string       `json:"status_msg,optional"` // 返回状态描述
	UserList   []FriendUser `json:"user_list"`           // 用户信息列表
}

type RelationFollowerListReq struct {
	Token  string `form:"token"`   // 用户鉴权token
	UserID string `form:"user_id"` // 用户id
}

type RelationFollowerListResp struct {
	StatusCode string `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg,optional"` // 返回状态描述
	UserList   []User `json:"user_list"`           // 用户列表
}

type RelationFriendListReq struct {
	Token  string `form:"token"`   // 用户鉴权token
	UserID string `form:"user_id"` // 用户id
}

type RelationFriendListResp struct {
	StatusCode string `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg,optional"` // 返回状态描述
	UserList   []User `json:"user_list"`           // 用户列表
}

type MessageActionReq struct {
	ActionType string `form:"action_type"` // 1-发送消息
	Content    string `form:"content"`     // 消息内容
	ToUserID   string `form:"to_user_id"`  // 对方用户id
	Token      string `form:"token"`       // 用户鉴权token
}

type MessageActionResp struct {
	StatusCode int64  `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg,optional"` // 返回状态描述
}

type MessageChatReq struct {
	ToUserID string `form:"to_user_id"` // 对方用户id
	Token    string `form:"token"`      // 用户鉴权token
}

type MessageChatResp struct {
	MessageList []Message `json:"message_list"`        // 用户列表
	StatusCode  string    `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg   string    `json:"status_msg,optional"` // 返回状态描述
}

type Message struct {
	Content    string `json:"content"`              // 消息内容
	CreateTime int64  `json:"create_time,optional"` // 消息发送时间 yyyy-MM-dd HH:MM:ss
	FromUserID int64  `json:"from_user_id"`         // 消息发送者id
	ID         int64  `json:"id"`                   // 消息id
	ToUserID   int64  `json:"to_user_id"`           // 消息接收者id
}


